stages:
  - test
  - deploy

django_test:
  stage: test
  image: python:3.10-alpine
  script:
    - apk update
    - apk add git
    - git clone https://github.com/farissatyaw/knowledge-test.git
    - pip install -r knowledge-test/coding-test/requirements.txt
    - python knowledge-test/coding-test/codingtest/manage.py test csvapi
deploy_to_kubernetes:
  stage: deploy
  image:
    name: alpine/helm
    entrypoint: [""]
  dependencies:
    - django_test
  script:
    - apk update
    - apk add git
    - git clone https://github.com/farissatyaw/knowledge-test.git
    - helm template knowledge-test/coding-test/manifests/codingtest/
