stages:
  - test
  - deploy

django_test:
  stage: test
  image: python:3.10
  script:
    - pip install -r coding-test/requirements.txt
    - python coding-test/codingtest/manage.py test csvapi
#deploy_to_kubernetes:
#  stage: deploy
#  image: alpine:latest
#  dependencies:
#    - django_test
#  script:
#    - apk add --no-cache bash
#    - helm upgrade --install codingtest coding-test/manifest/codingtest
